sudo: required
service:
 - docker
before_install:
  - docker build -t deenaramu/kub_vijay:v3.0 .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push deenaramu/kub_vijay:v3.0
notifications:
 email:
   recipients:
     - deenaramu@gmail.com
   on_success: always
   on_failure: always
